add github token

diff --git a/sample/bin/hie_low_memory b/sample/bin/hie_low_memory
--- a/sample/bin/hie_low_memory
+++ b/sample/bin/hie_low_memory
@@ -1,13 +1,65 @@
 #!/bin/bash
 
-if ! docker ps -a | grep hie > /dev/null 2>&1; then
-  docker run -i --rm -d \
-    -v ${HOME}/.ssh:/home/haskell/.ssh \
-    -v ${HOME}/.gitconfig:/home/haskell/.gitconfig \
-    -v $(pwd)/.hie-var/.stack:/home/haskell/.stack \
-    -v $(pwd):$(pwd) \
-    -v $(pwd)/.hie-var/.stack-work:$(pwd)/.stack-work \
-    -w $(pwd) \
-    --name hie pyar6329/hie:8.6.5
+if ! [ -e "$(pwd)/stack.yaml" ]; then
+  echo "Content-Length: 100\r\n\r"
+  echo '{"jsonrpc":"2.0","id":1,"error":{"code":-32099,"message":"Cannot find stack.yaml"}}'
+  exit 1
 fi
+
+if ! [ -e "$(pwd)/.stack-work" ]; then
+  mkdir -p $(pwd)/.stack-work
+fi
+
+if ! [ -e "$(pwd)/.var" ]; then
+  mkdir -p $(pwd)/.var
+fi
+
+if ! [ -e "$(pwd)/.var/.stack" ]; then
+  mkdir -p $(pwd)/.var/.stack
+fi
+
+if ! [ -e "$(pwd)/.var/.stack-work" ]; then
+  mkdir -p $(pwd)/.var/.stack-work
+fi
+
+GITCONFIG=$(cat << 'EOF'
+[credential]
+  helper = store
+[url "https://github.com/"]
+  insteadOf = ssh://git@github.com/
+  insteadOf = git@github.com:
+EOF
+)
+
+if [ -n "${GITHUB_TOKEN}" ]; then
+  if ! [ -e "$(pwd)/.var/.git-credentials" ]; then
+    echo "https://${GITHUB_TOKEN}:@github.com" > $(pwd)/.var/.git-credentials
+  fi
+  if ! [ -e "$(pwd)/.var/.gitconfig" ]; then
+    echo "${GITCONFIG}" > $(pwd)/.var/.gitconfig
+  fi
+  if ! docker ps -a | grep hie > /dev/null 2>&1; then
+    docker run -i --rm -d \
+      -v $(pwd):$(pwd) \
+      -v ${HOME}/.ssh:/home/haskell/.ssh \
+      -v $(pwd)/.var/.gitconfig:/home/haskell/.gitconfig \
+      -v $(pwd)/.var/.git-credentials:/home/haskell/.git-credentials \
+      -v $(pwd)/.var/.stack:/home/haskell/.stack \
+      -v $(pwd)/.var/.stack-work:$(pwd)/.stack-work \
+      -w $(pwd) \
+      --name hie pyar6329/hie:8.6.5
+  fi
+else
+  if ! docker ps -a | grep hie > /dev/null 2>&1; then
+    docker run -i --rm -d \
+      -v $(pwd):$(pwd) \
+      -v ${HOME}/.ssh:/home/haskell/.ssh \
+      -v ${HOME}/.gitconfig:/home/haskell/.gitconfig \
+      -v $(pwd)/.var/.stack:/home/haskell/.stack \
+      -v $(pwd)/.var/.stack-work:$(pwd)/.stack-work \
+      -w $(pwd) \
+      --name hie pyar6329/hie:8.6.5
+  fi
+fi
+
 exec docker exec -i hie hie +RTS -c -M4G -K4G -A128M -RTS --lsp
